# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YoKw9v4O9Fy7Dx1stFennzIHZz5FruZI

## Вводная часть
"""

import torch
import random
import numpy as np
import pandas as pd
import math

random.seed(0)
np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.backends.cudnn.deterministics = True

# Commented out IPython magic to ensure Python compatibility.
from sklearn import tree
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import files
uploaded = files.upload()

data = pd.read_excel('chd_patients.xlsx')

data

"""## Второе задание"""

chd_patients = data.loc[data.Patients == 'chd patient']
bins = math.ceil(1 + 3.332*np.log10(len(chd_patients)))
#sns.displot(chd_patients, x='Age', kind='kde', bw_adjust=.5) # только с ядерной оценкой плотности
sns.displot(chd_patients, x='Age', bins=bins, kde='True')

non_chd = data.loc[data.Patients == 'non-chd']
bins = math.ceil(1 + 3.332*np.log10(len(non_chd)))
#sns.displot(non_chd, x='Age', kind='kde', bw_adjust=.5) # только с ядерной оценкой плотности
sns.displot(non_chd, x='Age', bins=bins, kde='True')

bins = math.ceil(1 + 3.332*np.log10(len(data)))
sns.displot(data, x='Age', hue='Patients', bins=bins, kde='True')

"""Мы можем увидеть, что графики имеют нормальное распределение значений.
В предоставленных данных отсутствует информация о людях младше 50 лет без заболевания. В основном болеют люди в возрасте от 65 до 75. Людей с заболеванием примерно в 3-4 раза больше, чем здоровых людей.

## Третье задание
"""

sns.barplot(data, x='Patients', y='Age', hue='Gender');

sns.barplot(data, x='Patients', y='Age', hue='Smoker')

"""В выборке больше женщин, чем мужчин. Средний возраст у мужчин примерно на 10 лет меньше, чем у женщин, независимо от того, с заболеванием они или нет. У некурящих пациентов с заболеванием средний возраст примерно на 8 лет больше, чем у курящих, в то время как у здоровых пациентов эти показатели примерно одинаковые.

## Четвёртое задание
"""

sns.boxplot(data, x='Weight', y='Patients', hue='Gender', palette="Set2")

"""Из этого графика мы можем увидеть отсутствие корреляции между весом пациента и наличием у него заболевания, а также то, что у женщин вес меньше, чем у мужчин.

## Пятое задание
"""

sns.swarmplot(data, x='Weight', y='Patients', hue='Smoker', palette='husl');

"""Из графика мы видим, что курящих значительно меньше, чем некурящих, но никакой корреляции между курением и заболеваемостью мы не видим.

## Шестое задание
"""

import plotly.express as px
fig = px.scatter(data, x="Age",  y='Weight', symbol='Smoker', color='Patients')
fig.show()

"""Так как нам не были даны средние значения холестерина, я построил график зависимости веса от возраста, но этот график нам ничего не даёт, поэтому вывод по нему я сделать не могу, лишь только продемонстрировать тот факт, что я умею менять цвет и форму маркеров.

## Первое задание
"""

mu, sigma = 0, 1
rnd = np.random.normal(mu, sigma, 1000)
sns.displot(rnd, bins = 10)
sns.displot(rnd, bins = 50)